var questions = { screening: [
  {
    "group":"baseline_demographics",
    "type":"text",
    "content":"Kuzivikanwa kunoitwa murwere",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":"",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"text",
    "content":"Zita remuongororwi",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":"",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"text",
    "content":" Kero yemuongororwi",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":"",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"text",
    "content":"Nhamba dzerunhare dzaanobatika (1.Zita, 1.hukama; 2.Zita, 2.hukama)",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":"",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Mutauro unoshandiswa kumba kwemuongororwi",
    "response0":"Shona",
    "response0_value":"Shona",
    "response1":"English",
    "response1_value":"English",
    "response2":"Ndebele",
    "response2_value":"Ndebele",
    "response3":"Mumwe mutauro",
    "response3_value":"Mumwe mutauro",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Mutauro wehurukuro",
    "response0":"Shona",
    "response0_value":"Shona",
    "response1":"English",
    "response1_value":"English",
    "response2":"Mumwe mutauro",
    "response2_value":"Mumwe mutauro",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"text",
    "content":"Mavara anomirira zita remuongorori",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":"",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"text",
    "content":"Zuva reongororo",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":"",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"date",
    "content":"Zuva rawakaberekwa rinosvika rinhi? Zuva/mwedzi/gore(kana risingazivikanwi nyora makore)",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":"",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"text",
    "content":"Ndeipi dzidzo yepamusoro yawakaita?",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":"",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Unotendera muchitendero chipi?",
    "response0":"MuchiKristo, Roma",
    "response0_value":"MuchiKristo, Roma",
    "response1":"MuchiKristo, Postori",
    "response1_value":"MuchiKristo, Postori",
    "response2":"MuchiKristo, Dzemweya",
    "response2_value":"MuchiKristo, Dzemweya",
    "response3":"MuchiKristo, Savadha",
    "response3_value":"MuchiKristo, Savadha",
    "response4":"MuchiKristo, Zvapupu zva Jehovha",
    "response4_value":"MuchiKristo, Zvapupu zva Jehovha",
    "response5":"Muslim",
    "response5_value":"Muslim",
    "response6":"Zvimwe",
    "response6_value":"Zvimwe",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Muri kushanda here pari zvino?",
    "response0":"Handisi kushanda",
    "response0_value":"Handisi kushanda",
    "response1":"Zvenguva yose pabasa ",
    "response1_value":"Zvenguva yose pabasa ",
    "response2":"Zvedzimwe nguva pabasa   ",
    "response2_value":"Zvedzimwe nguva pabasa   ",
    "response3":"Zvemaricho",
    "response3_value":"Zvemaricho",
    "response4":"Zvekuzvishandira",
    "response4_value":"Zvekuzvishandira",
    "response5":"Handishande uye ndiri kutsvaga basa ",
    "response5_value":"Handishande uye ndiri kutsvaga basa ",
    "response6":"Handishande uye handisi kutsvaga basa",
    "response6_value":"Handishande uye handisi kutsvaga basa",
    "response7":"Zvimwe (Tsanangur)",
    "response7_value":"Zvimwe (Tsanangur)",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Ndeipi mari yaunowana inonyatsotsanangudza zvizere mari yaunoshandisa nemhuri mwedzi wega wega?",
    "response0":"1 - 50 US$",
    "response0_value":"1 - 50 US$",
    "response1":"51 -  100 US$",
    "response1_value":"51 -  100 US$",
    "response2":"101 � 200 US$",
    "response2_value":"101 � 200 US$",
    "response3":"201 � 500 US$",
    "response3_value":"201 � 500 US$",
    "response4":"Inopfuura  500 US$",
    "response4_value":"Inopfuura  500 US$",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Ndezvipi zvinonyanya kukupa mari?",
    "response0":"Basa remaoko",
    "response0_value":"Basa remaoko",
    "response1":"Yandinotambira",
    "response1_value":"Yandinotambira",
    "response2":"Mumwe wangu",
    "response2_value":"Mumwe wangu",
    "response3":"Kumhuri",
    "response3_value":"Kumhuri",
    "response4":"Handina yandinotambira",
    "response4_value":"Handina yandinotambira",
    "response5":"Zvimwe (Tsanangura)",
    "response5_value":"Zvimwe (Tsanangura)",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Wakaroora kana kuroorwa here?",
    "response0":"Ndakaroor(w)a ",
    "response0_value":"Ndakaroor(w)a ",
    "response1":"makarambana/ makasiyana",
    "response1_value":"makarambana/ makasiyana",
    "response2":"Wakafirwa",
    "response2_value":"Wakafirwa",
    "response3":"Uri kubika mapoto",
    "response3_value":"Uri kubika mapoto",
    "response4":"Hausati waroor(w)a",
    "response4_value":"Hausati waroor(w)a",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Wakaroor(w)a zviri pamutemo here?",
    "response0":"Kwete",
    "response0_value":"Kwete",
    "response1":"Hongu",
    "response1_value":"Hongu",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Wakaroor(w)a patsika dzechivanhu? ",
    "response0":"Kwete",
    "response0_value":"Kwete",
    "response1":"Hongu",
    "response1_value":"Hongu",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Mari yakabviswa here?",
    "response0":"Kwete",
    "response0_value":"Kwete",
    "response1":"Hongu",
    "response1_value":"Hongu",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Mumwe wako ane dzimwe shamwari dzaunoziva/dzausingazive here?",
    "response0":"Kwete",
    "response0_value":"Kwete",
    "response1":"Hongu, ane mumwe",
    "response1_value":"Hongu, ane mumwe",
    "response2":"Hongu, dzimwe mbiri",
    "response2_value":"Hongu, dzimwe mbiri",
    "response3":"Hongu, dzinopfuura mbiri",
    "response3_value":"Hongu, dzinopfuura mbiri",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"text",
    "content":"Iwe uri papi?",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":"",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Une vana here?",
    "response0":"Kwete",
    "response0_value":"Kwete",
    "response1":"Hongu",
    "response1_value":"Hongu",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"number",
    "content":"Une vangani vekubereka?",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":"",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"text",
    "content":"Vemazera api?",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":"",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"checkbox",
    "content":"Unochengeta vana vasiri vako here?",
    "response0":"Kwete",
    "response0_value":"Kwete",
    "response1":"Hongu, vazukuru",
    "response1_value":"Hongu, vazukuru",
    "response2":"Hongu, vamwewo",
    "response2_value":"Hongu, vamwewo",
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Vana vaunogara navo vanoenda kuchikoro here?",
    "response0":"Hongu",
    "response0_value":"Hongu",
    "response1":"Kwete",
    "response1_value":"Kwete",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Kana uine mumwe wako, ndeipi nzira yaanonyanya kuwana nayo mari?",
    "response0":"Kuzvishandira",
    "response0_value":"Kuzvishandira",
    "response1":"Anohora/Anotambira",
    "response1_value":"Anohora/Anotambira",
    "response2":"Murume kana mumwe wako",
    "response2_value":"Murume kana mumwe wako",
    "response3":"Iwe seshamwari kadzi/rume",
    "response3_value":"Iwe seshamwari kadzi/rume",
    "response4":"Haana kwaanowana mari",
    "response4_value":"Haana kwaanowana mari",
    "response5":"Zvimwewo (Tsanangura)",
    "response5_value":"Zvimwewo (Tsanangura)",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Une zvimwe zvezvinotevera muguta here?",
    "response0":"Imba",
    "response0_value":"Imba",
    "response1":"Imba yemubatanidzwa",
    "response1_value":"Imba yemubatanidzwa",
    "response2":"Imba isiri pamutemo",
    "response2_value":"Imba isiri pamutemo",
    "response3":"Hauna",
    "response3_value":"Hauna",
    "response4":"Aramba kutaura",
    "response4_value":"Aramba kutaura",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Une zvimwe zvezvinotevera here kumusha?",
    "response0":"Imba",
    "response0_value":"Imba",
    "response1":"Imba yemubatanidzwa",
    "response1_value":"Imba yemubatanidzwa",
    "response2":"Imba isiri pamutemo",
    "response2_value":"Imba isiri pamutemo",
    "response3":"Hauna",
    "response3_value":"Hauna",
    "response4":"Aramba kutaura",
    "response4_value":"Aramba kutaura",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Munogara muimba yakaita sei?",
    "response0":"Imba isiri pamutemo ",
    "response0_value":"Imba isiri pamutemo ",
    "response1":"Imba yekuseri",
    "response1_value":"Imba yekuseri",
    "response2":"Imba iri pamutemo",
    "response2_value":"Imba iri pamutemo",
    "response3":"Imba yemubatanidzwa/yekanzuru",
    "response3_value":"Imba yemubatanidzwa/yekanzuru",
    "response4":"Zvimwe (Tsanangura)",
    "response4_value":"Zvimwe (Tsanangura)",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"number",
    "content":"Kusanganisira newe, vanhu vakuru vangani vanogara mumba mako?",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":"",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"number",
    "content":"Vana vangani vanogara mumba mako?",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":"",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"number",
    "content":"Vanhu vangani vanorara mukamuri yaunorara iwe?",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":"",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Imarii yese pamwecheteinowanikwa yemumba mako pamwedzi?",
    "response0":"0 US$ ",
    "response0_value":"0 US$ ",
    "response1":"1 - 50 US$",
    "response1_value":"1 - 50 US$",
    "response2":"51 -  100 US$",
    "response2_value":"51 -  100 US$",
    "response3":"101 � 200 US$",
    "response3_value":"101 � 200 US$",
    "response4":"201 � 500 US$",
    "response4_value":"201 � 500 US$",
    "response5":"Inopfuura  500 US$",
    "response5_value":"Inopfuura  500 US$",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Mari iyi yakaenzana mwedzi wega wega here?",
    "response0":"Hongu yakaenzana mwedzi wega wega",
    "response0_value":"Hongu yakaenzana mwedzi wega wega",
    "response1":"Hongu, nguva zhinji inenge yakaenzana",
    "response1_value":"Hongu, nguva zhinji inenge yakaenzana",
    "response2":"Kwete, inosiyana zvakanyanya mwedzi nemwedzi",
    "response2_value":"Kwete, inosiyana zvakanyanya mwedzi nemwedzi",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Mune magetsi here kumba?",
    "response0":"Hongu",
    "response0_value":"Hongu",
    "response1":"Kwete",
    "response1_value":"Kwete",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Munowana mvura yemumba kupi?",
    "response0":"Matinogara",
    "response0_value":"Matinogara",
    "response1":"Munzvimbo",
    "response1_value":"Munzvimbo",
    "response2":"Kuvavakidzani",
    "response2_value":"Kuvavakidzani",
    "response3":"Papombi inoshandiswa nevamwe vanhuwo ",
    "response3_value":"Papombi inoshandiswa nevamwe vanhuwo ",
    "response4":"Hatiwane mvura nguva nenguva",
    "response4_value":"Hatiwane mvura nguva nenguva",
    "response5":"Zvimwe (Tsanangura)",
    "response5_value":"Zvimwe (Tsanangura)",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Mune chimbuzi chakaita sei?",
    "response0":"Chinoshandisa mvura  chekugojomora chiri mumba",
    "response0_value":"Chinoshandisa mvura  chekugojomora chiri mumba",
    "response1":"Chinoshandisa mvura chekugojomora chiri panze",
    "response1_value":"Chinoshandisa mvura chekugojomora chiri panze",
    "response2":"Chinoshandisa mvura chekugojomora chiri munharaunda",
    "response2_value":"Chinoshandisa mvura chekugojomora chiri munharaunda",
    "response3":"Chekudira mvura kana chegomba",
    "response3_value":"Chekudira mvura kana chegomba",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"checkbox",
    "content":"Une chimwe chezvinotevera here?",
    "response0":"Nhare mbozha ",
    "response0_value":"Nhare mbozha ",
    "response1":"Chivhitivhiti",
    "response1_value":"Chivhitivhiti",
    "response2":"Mbiya yemasaisai",
    "response2_value":"Mbiya yemasaisai",
    "response3":"Firiji",
    "response3_value":"Firiji",
    "response4":"Mubhedha",
    "response4_value":"Mubhedha",
    "response5":"Bhasikoro",
    "response5_value":"Bhasikoro",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Unoshandisa whatsapp here?",
    "response0":"Kwete",
    "response0_value":"Kwete",
    "response1":"Hongu",
    "response1_value":"Hongu",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Wakasununguka kutumira kana kutambira tsamba dzepanhare here?           ",
    "response0":"Kwete",
    "response0_value":"Kwete",
    "response1":"Hongu",
    "response1_value":"Hongu",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Wakamborwara nechirwere cherurindi?",
    "response0":"Kwete",
    "response0_value":"Kwete",
    "response1":"Hongu",
    "response1_value":"Hongu",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Unowana zvekudya kangani pazuva?",
    "response0":"Kamwe chete pazuva",
    "response0_value":"Kamwe chete pazuva",
    "response1":"Kaviri pazuva",
    "response1_value":"Kaviri pazuva",
    "response2":"Kanodarika kaviri pazuva",
    "response2_value":"Kanodarika kaviri pazuva",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Unonwa doro here?",
    "response0":"Kwete ",
    "response0_value":"Kwete ",
    "response1":"Hongu, zuva rega rega",
    "response1_value":"Hongu, zuva rega rega",
    "response2":"Hongu, svondo rega rega",
    "response2_value":"Hongu, svondo rega rega",
    "response3":"Hongu, mwedzi wega wega ",
    "response3_value":"Hongu, mwedzi wega wega ",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Unoputa here?",
    "response0":"Hongu",
    "response0_value":"Hongu",
    "response1":"Kwete",
    "response1_value":"Kwete",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Unorwara nechirwere chemunyama dzako chisingarapike?",
    "response0":"Kwete",
    "response0_value":"Kwete",
    "response1":"Hongu, BP",
    "response1_value":"Hongu, BP",
    "response2":"Hongu, shuga",
    "response2_value":"Hongu, shuga",
    "response3":"Hongu, rurindi",
    "response3_value":"Hongu, rurindi",
    "response4":"Hongu, chemabhonzo",
    "response4_value":"Hongu, chemabhonzo",
    "response5":"Hongu, zvimwe (Tsanangura)",
    "response5_value":"Hongu, zvimwe (Tsanangura)",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Unoziva mamiriro awakaita panyaya dze HIV?",
    "response0":"Kwete (chirika kuenda ku 45)",
    "response0_value":"Kwete (chirika kuenda ku 45)",
    "response1":"Hongu",
    "response1_value":"Hongu",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Wakapedzisira kuongororwa ropa rinhi?",
    "response0":"Pakati pemwedzi nemwedzi mitatu yapfuura",
    "response0_value":"Pakati pemwedzi nemwedzi mitatu yapfuura",
    "response1":"Kwapfuura mwedzi mitanhatu",
    "response1_value":"Kwapfuura mwedzi mitanhatu",
    "response2":"Kwapfuura gore rose",
    "response2_value":"Kwapfuura gore rose",
    "response3":"Kwapfuura makore maviri",
    "response3_value":"Kwapfuura makore maviri",
    "response4":"Handichayeuka",
    "response4_value":"Handichayeuka",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Kana mamiriro ako akarakidza kuti une hutachiwana, uri pamapiritsi eART here?",
    "response0":"Kwete (chirika zvimwe uende ku 41)",
    "response0_value":"Kwete (chirika zvimwe uende ku 41)",
    "response1":"Hongu",
    "response1_value":"Hongu",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Wakatanga rinhi kutora mapiritsi eART?",
    "response0":"<3months",
    "response0_value":"<3months",
    "response1":"<6months",
    "response1_value":"<6months",
    "response2":"<12months",
    "response2_value":"<12months",
    "response3":">12months",
    "response3_value":">12months",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Mamiriro ako arakidza kuti une hutachiwana, wakawaniswa kupangwa zano kunze kwekukurukurwa kwawakaitwa newe pawakaonekwa uine hutachiwana?",
    "response0":"Kwete (chirika kuenda ku43)",
    "response0_value":"Kwete (chirika kuenda ku43)",
    "response1":"Hongu",
    "response1_value":"Hongu",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Kupangwazano/rubatsiro kana kurapwa kwakadii?",
    "response0":"Wakapangwa semhuri",
    "response0_value":"Wakapangwa semhuri",
    "response1":"Kupangwazano kwerutsigiro",
    "response1_value":"Kupangwazano kwerutsigiro",
    "response2":"Kuchechi",
    "response2_value":"Kuchechi",
    "response3":"Shamwari",
    "response3_value":"Shamwari",
    "response4":"Kuhama",
    "response4_value":"Kuhama",
    "response5":"Kiriniki",
    "response5_value":"Kiriniki",
    "response6":"Zvimwewo",
    "response6_value":"Zvimwewo",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"checkbox",
    "content":"Une hutachiwana hwe HIV, pane wawakabudira pachena nezve mamiriro ako here?",
    "response0":"Kwete",
    "response0_value":"Kwete",
    "response1":"Hongu, mufundisi wekuchechi",
    "response1_value":"Hongu, mufundisi wekuchechi",
    "response2":"Hongu, shamwari dzangu zhinji dzekuchechi",
    "response2_value":"Hongu, shamwari dzangu zhinji dzekuchechi",
    "response3":"Hongu, mumwe wangu",
    "response3_value":"Hongu, mumwe wangu",
    "response4":"Hongu, Vemumhuri mangu vepedyo(vakoma, vanin�ina, hanzvadzi, vabereki)",
    "response4_value":"Hongu, Vemumhuri mangu vepedyo(vakoma, vanin�ina, hanzvadzi, vabereki)",
    "response5":"Hongu, vandinoshanda navo",
    "response5_value":"Hongu, vandinoshanda navo",
    "response6":"Hongu, vamwewo",
    "response6_value":"Hongu, vamwewo",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Hauna hutachiwana Hwe HIV, unogara uchienda kunoongororwa here?",
    "response0":"Hongu",
    "response0_value":"Hongu",
    "response1":"Kwete",
    "response1_value":"Kwete",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"checkbox",
    "content":"Ndeipi nzira yekuronga nayo mhuri yaunoshandisa?",
    "response0":"Hapana",
    "response0_value":"Hapana",
    "response1":"Makondomu",
    "response1_value":"Makondomu",
    "response2":"Mapiritsi",
    "response2_value":"Mapiritsi",
    "response3":"Yekubaiwa jekiseni",
    "response3_value":"Yekubaiwa jekiseni",
    "response4":"Rupu ",
    "response4_value":"Rupu ",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Nzira yako yekuronga nayo mhuri yakabudirira kwauri here?",
    "response0":"Hongu",
    "response0_value":"Hongu",
    "response1":"Kwete",
    "response1_value":"Kwete",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"checkbox",
    "content":"Chikonzero chaita kuti uuye kukiriniki chii nhasi?",
    "response0":"Zvinechekuita neHIV",
    "response0_value":"Zvinechekuita neHIV",
    "response1":"Zvimwe zvinechekuita nehutano",
    "response1_value":"Zvimwe zvinechekuita nehutano",
    "response2":"Zvinechekuita nepfungwa (Pfari, kurasa njere, kufungisisa, zvimwewo)",
    "response2_value":"Zvinechekuita nepfungwa (Pfari, kurasa njere, kufungisisa, zvimwewo)",
    "response3":"Kurwiswa /mhirizhonga/kubatwa chibharo",
    "response3_value":"Kurwiswa /mhirizhonga/kubatwa chibharo",
    "response4":"Kuzotora mapiritsi senguva dzose ehurwere husingarapike",
    "response4_value":"Kuzotora mapiritsi senguva dzose ehurwere husingarapike",
    "response5":"Kuuya nemwana anorwara/hama",
    "response5_value":"Kuuya nemwana anorwara/hama",
    "response6":"Kushaya mbereko",
    "response6_value":"Kushaya mbereko",
    "response7":"Kukiriniki yevakazvitakura",
    "response7_value":"Kukiriniki yevakazvitakura",
    "response8":"Zvimwewo",
    "response8_value":"Zvimwewo",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Mumwe wako akamira sei paHIV?",
    "response0":"Ane hutachiwana",
    "response0_value":"Ane hutachiwana",
    "response1":"Haana hutachiwana",
    "response1_value":"Haana hutachiwana",
    "response2":"Handina shamwari",
    "response2_value":"Handina shamwari",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Kana aine hutachiwana ari pamushonga here?",
    "response0":"Kwete",
    "response0_value":"Kwete",
    "response1":"Hongu",
    "response1_value":"Hongu",
    "response2":"Handizivi",
    "response2_value":"Handizivi",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"radio",
    "content":"Mumwe wako akamborwara neTB here?",
    "response0":"Kwete",
    "response0_value":"Kwete",
    "response1":"Hongu",
    "response1_value":"Hongu",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"baseline_demographics",
    "type":"checkbox",
    "content":"Wakambosangana nezvinokudzosera kumashure mumwedzi mitanhatu yapfuura here?",
    "response0":"Kwete",
    "response0_value":"Kwete",
    "response1":"Hongu, rufu rwemumwe wangu",
    "response1_value":"Hongu, rufu rwemumwe wangu",
    "response2":"Hongu, rufu rwemwana",
    "response2_value":"Hongu, rufu rwemwana",
    "response3":"Hongu, rufu rwemumwe wemumhuri",
    "response3_value":"Hongu, rufu rwemumwe wemumhuri",
    "response4":"Hongu, hurwere",
    "response4_value":"Hongu, hurwere",
    "response5":"Hongu, kurasikirwa nemari/nebasa",
    "response5_value":"Hongu, kurasikirwa nemari/nebasa",
    "response6":"Hongu, kurasikirwa nepokugara",
    "response6_value":"Hongu, kurasikirwa nepokugara",
    "response7":"Hongu, kushanduka kwemamiriro ezvinhu mumba/mhirizhonga",
    "response7_value":"Hongu, kushanduka kwemamiriro ezvinhu mumba/mhirizhonga",
    "response8":"Hongu, kurambwa",
    "response8_value":"Hongu, kurambwa",
    "response9":"Hongu, kurwiswa",
    "response9_value":"Hongu, kurwiswa",
    "response10":"Hongu, mhirizhonga",
    "response10_value":"Hongu, mhirizhonga",
    "response11":"Hongu, kubatwa chibharo",
    "response11_value":"Hongu, kubatwa chibharo",
    "response12":"",
    "response12_value":""
  }],
  ssq: [{
    "group":"ssq",
    "type":"p",
    "content":"Ndapota dzvanyai mubhokisi rimwechete chete",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":"",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"ssq",
    "type":"radio",
    "content":"Pane pandaimboona ndichinyanya kufungisisa kana kufunga zvakawanda",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Hongu",
    "response1_value":"10",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"ssq",
    "type":"radio",
    "content":"Pane pandaimbotadza kuisa pfungwa dzangu pamwechete",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Hongu",
    "response1_value":"10",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"ssq",
    "type":"radio",
    "content":"Pane pandaimboshatirwa kana kuita hasha zvenhando",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Hongu",
    "response1_value":"10",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"ssq",
    "type":"radio",
    "content":"Pane pandaimborota hope dzinotyisa kana dzisina kunaka.",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Hongu",
    "response1_value":"10",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"ssq",
    "type":"radio",
    "content":"Pane pandaimboona kana kunzwa zvinhu zvaisaonekwa kana kunzwikwa nevamwe",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Hongu",
    "response1_value":"10",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"ssq",
    "type":"radio",
    "content":"Pane pandaimborwadziwa nemudumbu",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Hongu",
    "response1_value":"10",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"ssq",
    "type":"radio",
    "content":"Pane pandaimbovhundutswa nezvinhu zvisina maturo",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Hongu",
    "response1_value":"10",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"ssq",
    "type":"radio",
    "content":"Pane pandaimbotadza kurara kana pandaishaiwa hope",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Hongu",
    "response1_value":"10",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"ssq",
    "type":"radio",
    "content":"Pane pandaimbonzwa kuomerwa neupenyu zvekuti ndaimbochema kana kunzwa kuda kuchema",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Hongu",
    "response1_value":"10",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"ssq",
    "type":"radio",
    "content":"Pane pandaimbonzwa kuneta",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Hongu",
    "response1_value":"10",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"ssq",
    "type":"radio",
    "name":"suicidevalid",
    "content":"Pane pandaimboita pfungwa dzekuda kuzviuraya",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Hongu",
    "response1_value":"10",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"ssq",
    "type":"radio",
    "content":"Ndaisafara nezvinhu zvandaiita zuva nezuva",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Hongu",
    "response1_value":"10",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"ssq",
    "type":"radio",
    "content":"Basa rangu rainge rava kusarira mumashure",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Hongu",
    "response1_value":"10",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  },
  {
    "group":"ssq",
    "type":"radio",
    "content":"Ndainzwa zvichindiomera kuti ndizive kuti ndoita zvipi",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Hongu",
    "response1_value":"10",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":"",
    "response4":"",
    "response4_value":"",
    "response5":"",
    "response5_value":"",
    "response6":"",
    "response6_value":"",
    "response7":"",
    "response7_value":"",
    "response8":"",
    "response8_value":"",
    "response9":"",
    "response9_value":"",
    "response10":"",
    "response10_value":"",
    "response11":"",
    "response11_value":"",
    "response12":"",
    "response12_value":""
  }],
  phq: [
  {
    "group":"PHQ9",
    "type":"p",
    "content":"Mumasvondo maviri apfuura makashungurudzwa  kangani nematambudziko anotevera",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":"",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":""
  },
  {
    "group":"PHQ9",
    "type":"radio",
    "content":"Kusanyatsova nechido chekuita zvinhu",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Mamwe mazuva",
    "response1_value":"1",
    "response2":"Zviri pakati nepakati",
    "response2_value":"2",
    "response3":"Zuva rega rega",
    "response3_value":"3"
  },
  {
    "group":"PHQ9",
    "type":"radio",
    "content":"Kusanyatsonzwa chido nezvehupenyu, kufunganya zvakapfuurikidza kana kushaya tariro muhupenyu",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Mamwe mazuva",
    "response1_value":"1",
    "response2":"Zviri pakati nepakati",
    "response2_value":"2",
    "response3":"Zuva rega rega",
    "response3_value":"3"
  },
  {
    "group":"PHQ9",
    "type":"radio",
    "content":"Kutadza kuwana hope kana kurara zvakapfuurikidza",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Mamwe mazuva",
    "response1_value":"1",
    "response2":"Zviri pakati nepakati",
    "response2_value":"2",
    "response3":"Zuva rega rega",
    "response3_value":"3"
  },
  {
    "group":"PHQ9",
    "type":"radio",
    "content":"Kunzwa kuneta uye kuve nesimba shoma rekuita zvinhu",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Mamwe mazuva",
    "response1_value":"1",
    "response2":"Zviri pakati nepakati",
    "response2_value":"2",
    "response3":"Zuva rega rega",
    "response3_value":"3"
  },
  {
    "group":"PHQ9",
    "type":"radio",
    "content":"Kusanyatsodya zvakakwana kana kudyisa",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Mamwe mazuva",
    "response1_value":"1",
    "response2":"Zviri pakati nepakati",
    "response2_value":"2",
    "response3":"Zuva rega rega",
    "response3_value":"3"
  },
  {
    "group":"PHQ9",
    "type":"radio",
    "content":"Kuzvizvidza pachezvako-kana kuti kunzwa sekuti urimukundikani muhupenyu  kana kutadza kuzadzikisa zvaitarisirwa nevemhuri yako",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Mamwe mazuva",
    "response1_value":"1",
    "response2":"Zviri pakati nepakati",
    "response2_value":"2",
    "response3":"Zuva rega rega",
    "response3_value":"3"
  },
  {
    "group":"PHQ9",
    "type":"radio",
    "content":"Kutadza kuita zvinhu zvakaita sekuverenga pepanhau nekuona chivhitivhiti pfungwa dziri pamwechete",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Mamwe mazuva",
    "response1_value":"1",
    "response2":"Zviri pakati nepakati",
    "response2_value":"2",
    "response3":"Zuva rega rega",
    "response3_value":"3"
  },
  {
    "group":"PHQ9",
    "type":"radio",
    "content":"Kufamba kana kutaura zvine kunonokera mukati zvekuti zvinogona zvakaonekwa nevamwe vakakutenderedza? Kana kuti kutadza kugarisika zvekuti wange urikufamba-famba zvakapfuurikidza zvaunofanirwa kunge uchiita",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Mamwe mazuva",
    "response1_value":"1",
    "response2":"Zviri pakati nepakati",
    "response2_value":"2",
    "response3":"Zuva rega rega",
    "response3_value":"3"
  },
  {
    "group":"PHQ9",
    "type":"radio",
    "content":"Kuve nendangariro dzekuti zvirinani kuti dai wafa zvakodu kana kuda kuzvikuvadza neimwe nzira",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Mamwe mazuva",
    "response1_value":"1",
    "response2":"Zviri pakati nepakati",
    "response2_value":"2",
    "response3":"Zuva rega rega",
    "response3_value":"3"
  },
  {
    "group":"PHQ9",
    "type":"radio",
    "content":"Kana muine matambudziko amakasangana nawo ari pamusoro, arikukutadzisai zvakadii kuita basa renyu, kuona kuti zvinhu zviri mugwara kumba kana kuwirirana nevamwe vanenge vakakukomberedzai?",
    "response0":"Kana",
    "response0_value":"Kana",
    "response1":"Zvishom a",
    "response1_value":"Zvishom a",
    "response2":"Zvakany anya",
    "response2_value":"Zvakany anya",
    "response3":"Zvakany anyisa",
    "response3_value":"Zvakany anyisa"
  }],
  suicide:[
  {
    "group":"suicide",
    "type":"radio",
    "content":"Evidence of suicidal intent",
    "response0":"no",
    "response0_value":"0",
    "response1":"yes",
    "response1_value":"1",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":""
  },
  {
    "group":"suicide",
    "type":"radio",
    "content":"Previous suicide attempt",
    "response0":"no",
    "response0_value":"0",
    "response1":"yes",
    "response1_value":"1",
    "response2":"",
    "response2_value":"",
    "response3":"",
    "response3_value":""
  }],
  lowssq: [
  {
    "group":"info",
    "type":"text",
    "content":"education",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":"",
    "response2":"",
    "response2_value":""
  },
  {
    "group":"info",
    "type":"text",
    "content":"mentor (support)",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":"",
    "response2":"",
    "response2_value":""
  },
  {
    "group":"info",
    "type":"radio",
    "content":"gender",
    "response0":"male",
    "response0_value":"0",
    "response1":"female",
    "response1_value":"1",
    "response2":"",
    "response2_value":""
  },
  {
    "group":"info",
    "type":"text",
    "content":"medical conditions",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":"",
    "response2":"",
    "response2_value":""
  },
  {
    "group":"info",
    "type":"text",
    "content":"How much are you in control of your life in terms of work, relationships, body, past and future?",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":"",
    "response2":"",
    "response2_value":""
  }],
  ies:[
  {
    "group":"IES",
    "type":"p",
    "content":"Zvinotevera matambudziko anowanzosangana nevanhu mushure mekunge vasangana nematambudziko ehupenyu anopa kushungurudzika mupfungwa. Tinokumbirisa kuti muverenge chimwe nechimwe pazvinotevera moratidza kuti ndechipi chakanyanya kukushungurudzai mumazuva manomwe apfuura maringe nedambudziko ramakasangana naro. Makakanganiswa zvakadii nezvinotevera?",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":null,
    "response2":"",
    "response2_value":null,
    "response3":"",
    "response3_value":null,
    "response4":"",
    "response4_value":null
  },
  {
    "group":"IES",
    "type":"radio",
    "content":"Chero mucherechedzo upi zvawo ndaibva ndanzwa kunge ndiri mukati medambudziko riya zvakare",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Zvishoma",
    "response1_value":1,
    "response2":"Zviripakati nepakati",
    "response2_value":2,
    "response3":"Zvikuru",
    "response3_value":3,
    "response4":"Zvikurusa",
    "response4_value":4
  },
  {
    "group":"IES",
    "type":"radio",
    "content":"Ndaiita dambudziko rekushaya hope",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Zvishoma",
    "response1_value":1,
    "response2":"Zviripakati nepakati",
    "response2_value":2,
    "response3":"Zvikuru",
    "response3_value":3,
    "response4":"Zvikurusa",
    "response4_value":4
  },
  {
    "group":"IES",
    "type":"radio",
    "content":"Zvimwe zvinhu zvaiita kuti ndifunge nezvedambudziko randakasanga naro iri",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Zvishoma",
    "response1_value":1,
    "response2":"Zviripakati nepakati",
    "response2_value":2,
    "response3":"Zvikuru",
    "response3_value":3,
    "response4":"Zvikurusa",
    "response4_value":4
  },
  {
    "group":"IES",
    "type":"radio",
    "content":"Ndainzwa kusvotwa nekugumbuka",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Zvishoma",
    "response1_value":1,
    "response2":"Zviripakati nepakati",
    "response2_value":2,
    "response3":"Zvikuru",
    "response3_value":3,
    "response4":"Zvikurusa",
    "response4_value":4
  },
  {
    "group":"IES",
    "type":"radio",
    "content":"Ndaizvidzora kubva pakugumbuka pandaifunga  kana kurangaridzwa nezvedambuziko randakasanga naro",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Zvishoma",
    "response1_value":1,
    "response2":"Zviripakati nepakati",
    "response2_value":2,
    "response3":"Zvikuru",
    "response3_value":3,
    "response4":"Zvikurusa",
    "response4_value":4
  },
  {
    "group":"IES",
    "type":"radio",
    "content":"Ndaifunga nezvazvo kunyangwe ndaisashuwira.",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Zvishoma",
    "response1_value":1,
    "response2":"Zviripakati nepakati",
    "response2_value":2,
    "response3":"Zvikuru",
    "response3_value":3,
    "response4":"Zvikurusa",
    "response4_value":4
  },
  {
    "group":"IES",
    "type":"radio",
    "content":"Ndainzwa sekunge zvisina kumbobvira zvaitika kana kuti zvaisave zvechokwadi",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Zvishoma",
    "response1_value":1,
    "response2":"Zviripakati nepakati",
    "response2_value":2,
    "response3":"Zvikuru",
    "response3_value":3,
    "response4":"Zvikurusa",
    "response4_value":4
  },
  {
    "group":"IES",
    "type":"radio",
    "content":"Ndainzvengana nezvinhu zvaindirangaridza izvi",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Zvishoma",
    "response1_value":1,
    "response2":"Zviripakati nepakati",
    "response2_value":2,
    "response3":"Zvikuru",
    "response3_value":3,
    "response4":"Zvikurusa",
    "response4_value":4
  },
  {
    "group":"IES",
    "type":"radio",
    "content":"Mifananidzo yezvakaitika yairamba ichidzoka mundangariro dzangu",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Zvishoma",
    "response1_value":1,
    "response2":"Zviripakati nepakati",
    "response2_value":2,
    "response3":"Zvikuru",
    "response3_value":3,
    "response4":"Zvikurusa",
    "response4_value":4
  },
  {
    "group":"IES",
    "type":"radio",
    "content":"Ndainge ndisina kugadzikana hana uye ndichingovhunduka nekukurumidza",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Zvishoma",
    "response1_value":1,
    "response2":"Zviripakati nepakati",
    "response2_value":2,
    "response3":"Zvikuru",
    "response3_value":3,
    "response4":"Zvikurusa",
    "response4_value":4
  },
  {
    "group":"IES",
    "type":"radio",
    "content":"Ndaiedza kusafunga nezvazvo",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Zvishoma",
    "response1_value":1,
    "response2":"Zviripakati nepakati",
    "response2_value":2,
    "response3":"Zvikuru",
    "response3_value":3,
    "response4":"Zvikurusa",
    "response4_value":4
  },
  {
    "group":"IES",
    "type":"radio",
    "content":"Ndaizviziva kuti ndainge ndichiri kushushikana  nezvazvo asi hapana zvandakaita kugadzirisa dambudziko iri",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Zvishoma",
    "response1_value":1,
    "response2":"Zviripakati nepakati",
    "response2_value":2,
    "response3":"Zvikuru",
    "response3_value":3,
    "response4":"Zvikurusa",
    "response4_value":4
  },
  {
    "group":"IES",
    "type":"radio",
    "content":"Hapana zvandainzwa kungave kurwadziwa, kushushikana kana kufunganya nezvazvo",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Zvishoma",
    "response1_value":1,
    "response2":"Zviripakati nepakati",
    "response2_value":2,
    "response3":"Zvikuru",
    "response3_value":3,
    "response4":"Zvikurusa",
    "response4_value":4
  },
  {
    "group":"IES",
    "type":"radio",
    "content":"Ndainzwa sekunge ndadzokera munguva yakaitika izvi",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Zvishoma",
    "response1_value":1,
    "response2":"Zviripakati nepakati",
    "response2_value":2,
    "response3":"Zvikuru",
    "response3_value":3,
    "response4":"Zvikurusa",
    "response4_value":4
  },
  {
    "group":"IES",
    "type":"radio",
    "content":"Ndaive nedambudziko mukuwana hope",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Zvishoma",
    "response1_value":1,
    "response2":"Zviripakati nepakati",
    "response2_value":2,
    "response3":"Zvikuru",
    "response3_value":3,
    "response4":"Zvikurusa",
    "response4_value":4
  },
  {
    "group":"IES",
    "type":"radio",
    "content":"Ndaive nenguva dzandaifunga  nezvazvo zvakanyanya",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Zvishoma",
    "response1_value":1,
    "response2":"Zviripakati nepakati",
    "response2_value":2,
    "response3":"Zvikuru",
    "response3_value":3,
    "response4":"Zvikurusa",
    "response4_value":4
  },
  {
    "group":"IES",
    "type":"radio",
    "content":"Ndakaedza kuzvibvisa mundangariro dzangu",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Zvishoma",
    "response1_value":1,
    "response2":"Zviripakati nepakati",
    "response2_value":2,
    "response3":"Zvikuru",
    "response3_value":3,
    "response4":"Zvikurusa",
    "response4_value":4
  },
  {
    "group":"IES",
    "type":"radio",
    "content":"Ndaive nedambudziko mukuita zvinhu pfungwa dziri pamwechete",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Zvishoma",
    "response1_value":1,
    "response2":"Zviripakati nepakati",
    "response2_value":2,
    "response3":"Zvikuru",
    "response3_value":3,
    "response4":"Zvikurusa",
    "response4_value":4
  },
  {
    "group":"IES",
    "type":"radio",
    "content":"Kurangaridzwa nezvazvo kwaiita kuti ndidikitire,kutadza kufema zvakanaka,kunzwa dzungu nekurohwa nehana zvakanyanya",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Zvishoma",
    "response1_value":1,
    "response2":"Zviripakati nepakati",
    "response2_value":2,
    "response3":"Zvikuru",
    "response3_value":3,
    "response4":"Zvikurusa",
    "response4_value":4
  },
  {
    "group":"IES",
    "type":"radio",
    "content":"Ndairota nezvazvo",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Zvishoma",
    "response1_value":1,
    "response2":"Zviripakati nepakati",
    "response2_value":2,
    "response3":"Zvikuru",
    "response3_value":3,
    "response4":"Zvikurusa",
    "response4_value":4
  },
  {
    "group":"IES",
    "type":"radio",
    "content":"Ndaigara ndakangorindira sezvingangoitika zvakare",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Zvishoma",
    "response1_value":1,
    "response2":"Zviripakati nepakati",
    "response2_value":2,
    "response3":"Zvikuru",
    "response3_value":3,
    "response4":"Zvikurusa",
    "response4_value":4
  },
  {
    "group":"IES",
    "type":"radio",
    "content":"Ndaiedza kusataura nezvazvo",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Zvishoma",
    "response1_value":1,
    "response2":"Zviripakati nepakati",
    "response2_value":2,
    "response3":"Zvikuru",
    "response3_value":3,
    "response4":"Zvikurusa",
    "response4_value":4
  }],
  whodas:[
  {
    "group":"WHODAS",
    "type":"p",
    "content":"Mumazuva makumi matatu apfuura, mungati makanetseka zvakadini  ku?",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":null,
    "response2":"",
    "response2_value":null,
    "response3":"",
    "response3_value":null,
    "response4":"",
    "response4_value":null
  },
  {
    "group":"WHODAS",
    "type":"radio",
    "content":"Kumira kwenguva yakareba yakafanana nemaminitsi makumi matatu(30 minutes) ?",
    "response0":"none",
    "response0_value":"1",
    "response1":"mild ",
    "response1_value":2,
    "response2":"moderate",
    "response2_value":3,
    "response3":"severe",
    "response3_value":4,
    "response4":"extreme or cannot do",
    "response4_value":5
  },
  {
    "group":"WHODAS",
    "type":"radio",
    "content":"Kuita basa repamba?",
    "response0":"none",
    "response0_value":"1",
    "response1":"mild ",
    "response1_value":2,
    "response2":"moderate",
    "response2_value":3,
    "response3":"severe",
    "response3_value":4,
    "response4":"extreme or cannot do",
    "response4_value":5
  },
  {
    "group":"WHODAS",
    "type":"radio",
    "content":"Kudzidzira zvinhu zvitsva senge kuziva kuti munoenda seyi kunzvimbo itsva?",
    "response0":"none",
    "response0_value":"1",
    "response1":"mild ",
    "response1_value":2,
    "response2":"moderate",
    "response2_value":3,
    "response3":"severe",
    "response3_value":4,
    "response4":"extreme or cannot do",
    "response4_value":5
  },
  {
    "group":"WHODAS",
    "type":"radio",
    "content":"Makanetseka zvakanyanya here kupinda mumitambo inoitwa munharaunda (senge mabiko, zvekumakereke kana zvimwewo) zvakafanana nevamwe vanhu?",
    "response0":"none",
    "response0_value":"1",
    "response1":"mild ",
    "response1_value":2,
    "response2":"moderate",
    "response2_value":3,
    "response3":"severe",
    "response3_value":4,
    "response4":"extreme or cannot do",
    "response4_value":5
  },
  {
    "group":"WHODAS",
    "type":"radio",
    "content":"Makanetseka zvakaita seyi mupfungwa nenyaya yematambudziko ehurwere?",
    "response0":"none",
    "response0_value":"1",
    "response1":"mild ",
    "response1_value":2,
    "response2":"moderate",
    "response2_value":3,
    "response3":"severe",
    "response3_value":4,
    "response4":"extreme or cannot do",
    "response4_value":5
  },
  {
    "group":"WHODAS",
    "type":"radio",
    "content":"Mumazuva makumi matatu apfuura, mungati makanetseka zvakadini  ku?",
    "response0":"none",
    "response0_value":"1",
    "response1":"mild ",
    "response1_value":2,
    "response2":"moderate",
    "response2_value":3,
    "response3":"severe",
    "response3_value":4,
    "response4":"extreme or cannot do",
    "response4_value":5
  },
  {
    "group":"WHODAS",
    "type":"radio",
    "content":"Kufamba pakareba senge kilometre kana pakafanana?",
    "response0":"none",
    "response0_value":"1",
    "response1":"mild ",
    "response1_value":2,
    "response2":"moderate",
    "response2_value":3,
    "response3":"severe",
    "response3_value":4,
    "response4":"extreme or cannot do",
    "response4_value":5
  },
  {
    "group":"WHODAS",
    "type":"radio",
    "content":"Kugeza muviri wako wese?",
    "response0":"none",
    "response0_value":"1",
    "response1":"mild ",
    "response1_value":2,
    "response2":"moderate",
    "response2_value":3,
    "response3":"severe",
    "response3_value":4,
    "response4":"extreme or cannot do",
    "response4_value":5
  },
  {
    "group":"WHODAS",
    "type":"radio",
    "content":"Kupfeka zvipfeko kana nhumbi?",
    "response0":"none",
    "response0_value":"1",
    "response1":"mild ",
    "response1_value":2,
    "response2":"moderate",
    "response2_value":3,
    "response3":"severe",
    "response3_value":4,
    "response4":"extreme or cannot do",
    "response4_value":5
  },
  {
    "group":"WHODAS",
    "type":"radio",
    "content":"Kutaura nevanhu vamusinga zive?",
    "response0":"none",
    "response0_value":"1",
    "response1":"mild ",
    "response1_value":2,
    "response2":"moderate",
    "response2_value":3,
    "response3":"severe",
    "response3_value":4,
    "response4":"extreme or cannot do",
    "response4_value":5
  },
  {
    "group":"WHODAS",
    "type":"radio",
    "content":"Kuchengeta hushamwari?",
    "response0":"none",
    "response0_value":"1",
    "response1":"mild ",
    "response1_value":2,
    "response2":"moderate",
    "response2_value":3,
    "response3":"severe",
    "response3_value":4,
    "response4":"extreme or cannot do",
    "response4_value":5
  },
  {
    "group":"WHODAS",
    "type":"radio",
    "content":"Basa renyu remazuva ese kana kuchikoro?",
    "response0":"none",
    "response0_value":"1",
    "response1":"mild ",
    "response1_value":2,
    "response2":"moderate",
    "response2_value":3,
    "response3":"severe",
    "response3_value":4,
    "response4":"extreme or cannot do",
    "response4_value":5
  },
  {
    "group":"WHODAS",
    "type":"number",
    "content":"Mukazvibatanidza mumazuva makumi matatu (30) apfuura,mazuva mangani pazvayiitika zvinhu izvi?",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":null,
    "response2":"",
    "response2_value":null,
    "response3":"",
    "response3_value":null,
    "response4":"",
    "response4_value":null
  },
  {
    "group":"WHODAS",
    "type":"number",
    "content":"Mumazuva makumi matatu apfuura (30) makatadzisisa kuita basa renyu remazuva ose here nekuda kwehurwere?",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":null,
    "response2":"",
    "response2_value":null,
    "response3":"",
    "response3_value":null,
    "response4":"",
    "response4_value":null
  },
  {
    "group":"WHODAS",
    "type":"number",
    "content":"Mumazuva makumi matatu apfuura (30) musingaverengeri mazuva amakatadza zvachose, mazuva mangani amakaita zvishoma pane zvamunosiyiita kana kushanda nekuda kwehurwere?",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":null,
    "response2":"",
    "response2_value":null,
    "response3":"",
    "response3_value":null,
    "response4":"",
    "response4_value":null
  }],
  eq:[
  {
    "group":"EQ_5D_5L",
    "type":"h1",
    "content":"Mibvunzo yezvehutano",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":null,
    "response2":"",
    "response2_value":null,
    "response3":"",
    "response3_value":null,
    "response4":"",
    "response4_value":null
  },
  {
    "group":"EQ_5D_5L",
    "type":"h1",
    "content":"Gwaro reChirungu reku UK",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":null,
    "response2":"",
    "response2_value":null,
    "response3":"",
    "response3_value":null,
    "response4":"",
    "response4_value":null
  },
  {
    "group":"EQ_5D_5L",
    "type":"p",
    "content":"Pamusoro wenyaya wega wega ndapota isa mucherechedzo mubhokisi  RIMWECHETE rinonyatsotsanangura hutano hwako NHASI.",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":null,
    "response2":"",
    "response2_value":null,
    "response3":"",
    "response3_value":null,
    "response4":"",
    "response4_value":null
  },
  {
    "group":"EQ_5D_5L",
    "type":"radio",
    "content":"ZVEKUFAMBA",
    "response0":"Handina dambudziko pakufamba famba",
    "response0_value":"1",
    "response1":"Ndine kadambudziko pakufamba famba",
    "response1_value":2,
    "response2":"Ndine dambudziko zviri pakati nepakati pakufamba famba",
    "response2_value":3,
    "response3":"Ndine dambudziko rakanyanya pakufamba famba",
    "response3_value":4,
    "response4":"Handikwanise kufamba",
    "response4_value":5
  },
  {
    "group":"EQ_5D_5L",
    "type":"radio",
    "content":"ZVEKUZVICHENGETEDZA",
    "response0":"Handina dambudziko pakuzvigeza kana kuzvipfekedza",
    "response0_value":"1",
    "response1":"Ndine kadambudziko pakuzvigeza kana kuzvipfekedza",
    "response1_value":2,
    "response2":"Ndine dambudziko zviri pakati nepakati pakuzvigeza kana kuzvipfekedza",
    "response2_value":3,
    "response3":"Ndine dambudziko rakanyanya pakuzvigeza kana kuzvipfekedza",
    "response3_value":4,
    "response4":"Handikwanise kuzvigeza kana kuzvipfekedza",
    "response4_value":5
  },
  {
    "group":"EQ_5D_5L",
    "type":"radio",
    "content":"ZVINOITWA NGUVA DZOSE (semuenzaniso, basa, kuverenga, basa remumba, mhuri kana zvemafaro)",
    "response0":"Handina dambudziko pakuita zvandinofanira kuita nguva dzose",
    "response0_value":"1",
    "response1":"Ndine kadambudziko pakuita zvandinofanira kuita nguva dzose",
    "response1_value":2,
    "response2":"Ndine dambudziko zviri pakati nepakati pakuita zvandinofanira kuita nguva dzose",
    "response2_value":3,
    "response3":"Ndine dambudziko rakanyanya pakuita zvandinofanira kuita nguva dzose",
    "response3_value":4,
    "response4":"Handigone kuita zvandinofanira kuita nguva dzose ",
    "response4_value":5
  },
  {
    "group":"EQ_5D_5L",
    "type":"radio",
    "content":"MARWADZO/ KUSAGADZIKANA",
    "response0":"Handina marwadzo kana kusagadzikana",
    "response0_value":"1",
    "response1":"Ndine tumarwadzo nekusagadzikana kushoma",
    "response1_value":2,
    "response2":"Ndine marwadzo nekusagadzikana zviri pakati nepakati",
    "response2_value":3,
    "response3":"Ndine marwadzo nekusagadzikana zvakanyanya",
    "response3_value":4,
    "response4":"Ndine marwadzo nekusagadzikana kwakapfurikidza",
    "response4_value":5
  },
  {
    "group":"EQ_5D_5L",
    "type":"radio",
    "content":"KUSAGADZIKANA MUPFUNGWA/ KUFUNGISISA",
    "response0":"Handina kusagadzikana mupfungwa kana kufungisisa",
    "response0_value":"1",
    "response1":"Ndine kakusagadzikana mupfungwa kana kufungisisa zvishoma",
    "response1_value":2,
    "response2":"Ndine kusagadzikana mupfungwa kana kufungisisa zviri pakati nepakati",
    "response2_value":3,
    "response3":"Ndine kusagadzikana mupfungwa kana kufungisisa zvakanyanya",
    "response3_value":4,
    "response4":"Ndine kusagadzikana mupfungwa kana kufungisisa zvakapfurikidza",
    "response4_value":5
  }],
  gad:[
  {
    "group":"GAD7",
    "type":"p",
    "content":"Mumasvondo maviri apfuura, makashungurudzwa zvakadii nematambudziko anotevera?",
    "response0":"",
    "response0_value":"",
    "response1":"",
    "response1_value":null,
    "response2":"",
    "response2_value":null,
    "response3":"",
    "response3_value":null,
    "response4":"",
    "response4_value":null
  },
  {
    "group":"GAD7",
    "type":"radio",
    "content":"Ndainzwa kugarotya, kutambudzika nekushushikana",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Mamwe mazuva",
    "response1_value":1,
    "response2":"Mazuva akati wandei",
    "response2_value":2,
    "response3":"Zuva nezuva",
    "response3_value":3,
    "response4":"",
    "response4_value":null
  },
  {
    "group":"GAD7",
    "type":"radio",
    "content":"Kutadza kuregedza kushushikana mupfungwa",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Mamwe mazuva",
    "response1_value":1,
    "response2":"Mazuva akati wandei",
    "response2_value":2,
    "response3":"Zuva nezuva",
    "response3_value":3,
    "response4":"",
    "response4_value":null
  },
  {
    "group":"GAD7",
    "type":"radio",
    "content":"Kushushikana zvakanyanya nekuda kwezvinhu zvakasiyana- siyana",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Mamwe mazuva",
    "response1_value":1,
    "response2":"Mazuva akati wandei",
    "response2_value":2,
    "response3":"Zuva nezuva",
    "response3_value":3,
    "response4":"",
    "response4_value":null
  },
  {
    "group":"GAD7",
    "type":"radio",
    "content":"Kutadza kuzorora zvakanaka",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Mamwe mazuva",
    "response1_value":1,
    "response2":"Mazuva akati wandei",
    "response2_value":2,
    "response3":"Zuva nezuva",
    "response3_value":3,
    "response4":"",
    "response4_value":null
  },
  {
    "group":"GAD7",
    "type":"radio",
    "content":"Kushushikana zvekuti kugarisika kwainetsa",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Mamwe mazuva",
    "response1_value":1,
    "response2":"Mazuva akati wandei",
    "response2_value":2,
    "response3":"Zuva nezuva",
    "response3_value":3,
    "response4":"",
    "response4_value":null
  },
  {
    "group":"GAD7",
    "type":"radio",
    "content":"Kukurumidza kusvotwa nezvinhu",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Mamwe mazuva",
    "response1_value":1,
    "response2":"Mazuva akati wandei",
    "response2_value":2,
    "response3":"Zuva nezuva",
    "response3_value":3,
    "response4":"",
    "response4_value":null
  },
  {
    "group":"GAD7",
    "type":"radio",
    "content":"Kunzwa kutya kuti kungangoitike chinhu chakaipa",
    "response0":"Kwete",
    "response0_value":"0",
    "response1":"Mamwe mazuva",
    "response1_value":1,
    "response2":"Mazuva akati wandei",
    "response2_value":2,
    "response3":"Zuva nezuva",
    "response3_value":3,
    "response4":"",
    "response4_value":null
  }]
};


/*var transformAll = [
	{"tag":"div", "class":"container"},
	{"tag":"ul", children:function(){return(json2html.transform(this.question, transformRadio));}}
	];*/
	
/*_.each(questions, function(e,i){console.log(e,i)});
*/
var transformRadio =
{"tag":"div","class":"btn-group","data-toggle":"buttons","html":"<p>${content}</p>","children":[
    {"tag":"label","class":"btn btn-primary ${group}","children":[
    	{"tag":"input","type":"radio","name":"${name}","value":"${response0_value}","html":"${response0}"}
    ]},
    {"tag":"label","class":"btn btn-primary ${group}","children":[
    	{"tag":"input","type":"radio","name":"${name}","value":"${response1_value}","html":"${response1}"}
    ]},
    {"tag":"label","class":"btn btn-primary ${group}","children":[
    	{"tag":"input","type":"radio","value":"${response2_value}","html":"${response2}"}
    ]},
    {"tag":"label","class":"btn btn-primary ${group}","children":[
    	{"tag":"input","type":"radio","value":"${response3_value}","html":"${response3}"}
    ]},
    {"tag":"label","class":"btn btn-primary ${group}","children":[
    	{"tag":"input","type":"radio","value":"${response4_value}","html":"${response4}"}
    ]},
    {"tag":"label","class":"btn btn-primary ${group}","children":[
        {"tag":"input","type":"radio","value":"${response5_value}","html":"${response5}"}
    ]},
    {"tag":"label","class":"btn btn-primary ${group}","children":[
        {"tag":"input","type":"radio","value":"${response6_value}","html":"${response6}"}
    ]},
    {"tag":"label","class":"btn btn-primary ${group}","children":[
        {"tag":"input","type":"radio","value":"${response7_value}","html":"${response7}"}
    ]},
    {"tag":"label","class":"btn btn-primary ${group}","children":[
        {"tag":"input","type":"radio","value":"${response8_value}","html":"${response8}"}
    ]},
    {"tag":"label","class":"btn btn-primary ${group}","children":[
        {"tag":"input","type":"radio","value":"${response9_value}","html":"${response9}"}
    ]},
    {"tag":"label","class":"btn btn-primary ${group}","children":[
        {"tag":"input","type":"radio","value":"${response10_value}","html":"${response10}"}
    ]},
    {"tag":"label","class":"btn btn-primary ${group}","children":[
        {"tag":"input","type":"radio","value":"${response11_value}","html":"${response11}"}
    ]},
    {"tag":"label","class":"btn btn-primary ${group}","children":[
        {"tag":"input","type":"radio","value":"${response12_value}","html":"${response12}"}
    ]},
    {"tag":"label","class":"btn btn-primary ${group}","children":[
        {"tag":"input","type":"radio","value":"${response13_value}","html":"${response13}"}
    ]}
]}; //some way to condense this code?

/*var transformCheckbox =
{"tag":"div","class":"btn-group","data-toggle":"buttons","html":"<p>${content}</p>","children":[
    {"tag":"label","class":"btn btn-primary","children":[
    	{"tag":"input","type":"checkbox","html":"${response0}"}
    ]},
    {"tag":"label","class":"btn btn-primary","children":[
    	{"tag":"input","type":"checkbox","html":"${response1}"}
    ]},
    {"tag":"label","class":"btn btn-primary","children":[
    	{"tag":"input","type":"checkbox","html":"${response2}"}
    ]},
    {"tag":"label","class":"btn btn-primary","children":[
    	{"tag":"input","type":"checkbox","html":"${response3}"}
    ]},
    {"tag":"label","class":"btn btn-primary","children":[
    	{"tag":"input","type":"checkbox","html":"${response4}"}
    ]}
]};*/
var transformCheckbox =
{"tag":"div","class":"btn-group","data-toggle":"buttons","html":"<p>${content}</p>","children":[
    {"tag":"label","class":"btn btn-info ${group}","children":[
        {"tag":"input","type":"checkbox","html":"${response0}"}
    ]},
    {"tag":"label","class":"btn btn-info ${group}","children":[
        {"tag":"input","type":"checkbox","html":"${response1}"}
    ]},
    {"tag":"label","class":"btn btn-info ${group}","children":[
        {"tag":"input","type":"checkbox","html":"${response2}"}
    ]},
    {"tag":"label","class":"btn btn-info ${group}","children":[
        {"tag":"input","type":"checkbox","html":"${response3}"}
    ]},
    {"tag":"label","class":"btn btn-info ${group}","children":[
        {"tag":"input","type":"checkbox","html":"${response4}"}
    ]}
]};

for (var i=0; i < 12; i++) {
    console.log("${response"+i+"}");
};
var transformText =
{"tag":"div","class":"form-group","html":"${content}","children":[
	{"tag":"input","type":"text","class":"form-control"}
]};

var transformNumber =
{"tag":"div", "class":"panel panel-default","children":[
   {"tag":"div","class":"panel-body","html":"${content} <br />","children":[
       {"tag":"input","type":"number","min":"0"}
    ]}
]};

var transformParagraph = {"tag":"p", "html":"${content}"};

var transformDate =
	[{"tag":"p", "html":"${content}"},
    {"tag":"input","type":"date"}];

var transformH1 = {"tag":"h1", "html":"${content}"};

$.each(questions, function(category, items) {
    console.log(category);
    $.each(items, function(idx,question) {
        if (question.type === "radio") {
            $('#' + category).json2html(this,transformRadio);
        }
        else if (question.type === "text") {
            $('#' + category).json2html(this,transformText);
        }
        else if (question.type === "number") {
            $('#' + category).json2html(this,transformNumber);
        }
        else if (question.type === "date") {
            $('#' + category).json2html(this,transformDate);
        }
        else if (question.type === "checkbox") {
            $('#' + category).json2html(this, transformCheckbox);
        }
        else if (question.type === "p") {
            $('#' + category).json2html(this, transformParagraph);
        }
        else if (question.type === "h1") {
            $('#' + category).json2html(this, transformH1);
        }
        else {
            console.log(this.type);
        }
    });
});
$(document).ready(function() {
	$('input[type=radio]').each(function() {
		if ($(this).val() === "") {
			$(this).parent().remove(); /* remove any empty radio buttons */
		}
	});
	$("#start").click(function() {
		$("#survey").show("slow"); /* start animation with "Start" button */
	});
});
$(function() {
    FastClick.attach(document.body);
});